baseURL = "https://nerdcoach.io/"
languageCode = "en-us"
publishDir = "docs/"
title = "Nerd Coach"
googleAnalytics = "UA-113472270-2" 
enableEmoji = true
disableKinds = ["taxonomy", "taxonomyTerm"]
[params]
    author = "Carl Tashian"
    description = "I'm here to help you move from a IC role into leadership."
    favicon = "favicon.png"

