baseURL = "https://nerdcoach.io/"
languageCode = "en-us"
publishDir = "docs/"
title = "Nerd Coach"
theme = "nerdcoach"
googleAnalytics = "UA-113472270-2" 
[params]
    author = "Carl Tashian"
    description = "I work with engineering managers and founders to become more confident and effective leaders."
    favicon = "favicon.png"
